### PR TITLE
Add TOC scroll highlighting feature

### PR DESCRIPTION
**Pull request by ndianabasi**
This PR adds the feature for highlighting the visitors current position while reading the docs.

The IntersectionObserver API was used. No external dependencies.

Features included:
1. tracking only in-page header links which exist on the TOC.
2. tracking of headers with long section which causes the header to scroll out of view before the next header appears.
3. Same highlight style as nav menu is used for TOC.
4. Can show multiple highlights if multiple tracked headers are in view.

### CODE REVIEW

**Comment by thetutlage** [comment]
The PR also has a doc change. Can we remove that and keep it focused on must the scroll highlighting feature?

**Comment by ndianabasi** [comment]
How do I remove the last commit from the PR?

**Comment by ndianabasi** [comment]
I've removed the doc change.

**Comment by thetutlage** [comment]
Thanks. Can you please also share how it is expected to work. When I see the toc sidebar, it has more than one active links at a time.

Screen Shot 2021-05-22 at 7 00 46 PM
Screen Shot 2021-05-22 at 7 00 58 PM

How does other websites do it?

**Comment by ndianabasi** [comment]
The aim of the highlighting is to show visitors which section of the current page they are currently viewing. The AdonisJS docs have many short sections. In some cases up to 3 headers can be in the view. That is why you see multiple TOC items highlighted.

If that behavious isn't desirable, I can make it show one hightlight at time even though there are multiple headers in the view.  There is an example from [Nuxt docs](https://nuxtjs.org/docs/2.x/get-started/installation) which shows only one highlight at a time. But I don't think it is a standard. AdonisJS can go for a different behaviour. It is your call.

**Comment by RomainLanz** [comment]
Hey @ndianabasi! 👋 

Yes, it would be better to have one highlight at a time.
Also, I believe the styling should be more subtle like only increase the color's contrast.

**Comment by thetutlage** [comment]
Works only once and then it stops working

CleanShot 2021-05-29 at 09 54 41

**Comment by ndianabasi** [comment]
Hello. I didn't get any feedback again after pushing the new commit.

**Comment by thetutlage** [comment]
@ndianabasi I see the PR has merge conflicts. Can you please fix them and then I will try it on my local :)

**Comment by ndianabasi** [comment]
Hi @thetutlage. I'm getting a 500 error with the message:

 ```text
'ENOENT: no such file or directory, open \'F:\\docs.adonisjs.com\\node_modules\\shiki\\themes\\material-palenight.json\''
```

after successfully merging my fork.

**Comment by ndianabasi** [comment]
I've fixed the above error in the last commit.

**Comment by thetutlage** [comment]
There are few issues with the PR that makes me hesitant of merging it.

- There are one of errors getting logged in the console (see screenshot for that).
- The code is unnecessarily complex. There are way too many nested if statements. Must be cleaned up
- The PR includes other changes as well. There is one doc change and then you have also updated the color scheme from `material-palenight` to `material-theme-palenight`.

Screenshot 2021-08-06 at 9 09 56 AM

Screenshot 2021-08-06 at 9 10 08 AM

**Comment by thetutlage** [comment]
Closing since not actionable

**Pull request closed without merging**
