### PR TITLE
docs: add documentation about new Lucid commands

### PR DESCRIPTION
**Pull request by Julien-R44**
I have added documentation about the new Lucid commands that I proposed in my PR : https://github.com/adonisjs/lucid/pull/764

### CODE REVIEW

**Comment by thetutlage** [comment]
Waiting to release Lucid first

**Comment by Julien-R44** [comment]
I don't seem to have the rights on this repo to do it, so just a little reminder that we should merge this + #115 + #124

**Comment by RomainLanz** [comment]
Done 👍🏻

**Comment by thetutlage** [comment]
@Julien-R44 Given rights to you. However, I still suggest getting PR's peer reviewed before the merge :)

**Pull request merged**
