### PR TITLE
Added cookbook for dockerizing adonis

### PR DESCRIPTION
**Pull request by hlozancic**

### CODE REVIEW

**Comment by hlozancic** [comment]
If needed I can add basic stuff like how to run docker image, which port it will listen too, etc... 
But wanted to explain something that is not not so basic in cookbook

**Comment by hlozancic** [comment]
@thetutlage any feedback would be great... I will have more spare time soon, just want to know if you want more of content like this in general.

**Comment by thetutlage** [comment]
Looks good to me from the technical point of view. Will you okay, if I am modify some of the language in the cookbook?

**Comment by hlozancic** [comment]
> Looks good to me from the technical point of view. Will you okay, if I am modify some of the language in the cookbook?

Sure, you can change anything. Also if you dont't like something or want more info about some other topic, just let me know. It's not a problem

**Comment by thetutlage** [comment]
Thanks for the PR and sorry for taking so long

**Comment by hlozancic** [comment]
Thanks Virk! No, problem... I know you are busy developing more cool stuff :)

**Comment by brkn** [comment]
@hlozancic What would you recommend for running migrations when using `docker-compose`?

**Comment by hlozancic** [comment]
> @hlozancic What would you recommend for running migrations when using `docker-compose`?

I personally just run `node ace migration:run` outside of docker (in my project root). This works as expected if you are using docker-compose from this cookbook because database is exposed to host machine.

You can always attach to docker container itself and run it there too.

**Pull request merged**
