### PR TITLE
Update trim.md

### PR DESCRIPTION
**Pull request by dimitrisnl**
### ❓ Type of change

- [X] 🐞 Bug fix (a non-breaking change that fixes an issue)

### 📚 Description

Correcting a typo

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by RomainLanz** [comment]
Thanks!

**Comment by Julien-R44** [comment]
I'm far from being a native English speaker, but I believe that "whitespace" must actually be in the plural form here

**Comment by Julien-R44** [comment]
Oops @RomainLanz was too fast ahah

**Comment by RomainLanz** [comment]
> I'm far from being a native English speaker, but I believe that "whitespace" must actually be in the plural form here

`whitespace` is uncountable, same with `middleware` 😄

**Comment by Julien-R44** [comment]
Oooh okay I didn't know, thanks ahaha 😄

**Pull request merged**
