### PR TITLE
Add resource example when using middleware

### PR DESCRIPTION
**Pull request by MrAvantiC**
Today I stumbled across the same question that was asked here:
https://github.com/adonisjs/core/discussions/1469

I think it would be useful to have this included in the documentation.

### CODE REVIEW

**Comment by thetutlage** [comment]
I believe the resources guide already cover that. https://docs.adonisjs.com/guides/controllers#applying-middleware

Maybe, we can add a complete section to the middleware guide that explains how to apply middleware to a route, a resource and a group. In case of group we should also explain that group middleware are applied first?

**Comment by MrAvantiC** [comment]
Hey @thetutlage ,
oh my bad! I guess I looked in the wrong places when researching my question.

I'm just getting started with AdonisJS and wanted to make a small contribution. Not sure I can already explain all the different variations that you mentioned myself.

**Comment by RomainLanz** [comment]
Hey! 👋🏻 

In fact, those are not on the same section, so maybe we can add a link so people can navigate to the information?

**Comment by thetutlage** [comment]
@RomainLanz Yup. Not a bad idea. Instead of repeating the info, we can link to the relevant doc(s)

**Comment by MrAvantiC** [comment]
I removed the duplicate explanation and referenced the section that @thetutlage mentioned.

**Comment by RomainLanz** [comment]
Thanks!

**Pull request merged**
