### PR TITLE
Add examples how to stream files

### PR DESCRIPTION
**Pull request by D-Marc1**
Porting over my examples from the [legacy docs](https://github.com/adonisjs/legacy.adonisjs.com/pull/126).

### CODE REVIEW

**Comment by thetutlage** [comment]
Hello 👋

Thanks for the PR. Is it possible to add some explanation around where one should use `directUploads` over the standard one and the constraints attached to direct uploads as well.

**Comment by D-Marc1** [comment]
I honestly don't know too much about this topic to give a proper explanation. I just figured these coding examples would be useful for people who want to know how to stream files directly in Adonis, without having to use a tmp directory.

**Comment by thetutlage** [comment]
No worries. I am already planning to write on this topic, so will reference and see if your examples can be used in the final doc. Thanks again for taking out the time :)

**Comment by D-Marc1** [comment]
Sure, no problem. Happy to help improve the Adonis docs. Was no effort at all really. Had these examples from previous projects I did in Adonis.

**Comment by thetutlage** [comment]
Added the direct uploads guide in this commit. https://github.com/adonisjs/docs.adonisjs.com/commit/040b970c68b3eaf85a4397cc0737f7988fab787e.

We have kept it implementation agnostic and focused on the general API that one should be able to translate for the SDK of their choice.

Thanks again for putting in the efforts. I am more than happy to accept a PR for service specific (ie S3) cookbook.

**Comment by D-Marc1** [comment]
Sure, no problem. I personally think it was a mistake for you to leave out many important topics I covered here, like how to upload multiple files and multiple files with distinct names, as this is definitely not obvious. Additionally, you write that you can't access input fields before processing the file, but this isn't entirely correct, as I showed in my example here. You can pass them in as URL parameters, rather than in the body.

**Comment by thetutlage** [comment]
> Additionally, you write that you can't access input fields before processing the file, but this isn't entirely correct, as I showed in my example here. You can pass them in as URL parameters, rather than in the body.

Input fields and request params are not the same thing. Input fields are form input fields.

> I personally think it was a mistake for you to leave out many important topics I covered here, like how to upload multiple files and multiple files with distinct names, as this is definitely not obvious

Can you share an example of same?

**Comment by D-Marc1** [comment]
> Input fields and request params are not the same thing. Input fields are form input fields.

It doesn't matter what you call it. It should be made clear (IMHO) that while you can't use text data before processing the file, if the text data is passed into body, you can use text data before processing the file, if you pass it in as URL parameters.  I don't think that would be obvious to anyone by just looking at the docs.

> Can you share an example of same?

They're all in my pull request here.

You're free to omit all these things I added here and talked about in my comments, as it's your framework, after all. I just think it would make sense to add them, as it's pretty common to upload multiple files for instance. People are likely going to google all these things I mentioned here or just search on the GitHub discussions. Just think it would make sense to add them to the docs, but that's just my two cents. At least I can always refer back to this pull request for myself.

**Pull request closed without merging**
