### PR TITLE
feat: add "Packages" to desktop navbar

### PR DESCRIPTION
**Pull request by Julien-R44**
I added a link to our Packages site on the documentation. Most of the framework regulars don't go to the landing page but directly to the documentation, and a lot of them might not even be aware of the existence of our packages site !
I didn't add it on mobile but if you think it's necessary let me know 👍 

image

### CODE REVIEW

**Comment by thetutlage** [comment]
I think, we can add a dropdown called `About` and then add `News`, `Packages` and `Releases` inside it.

**Comment by Julien-R44** [comment]
Good idea! Concerning the release page, just to be sure, you want this page ( https://docs.adonisjs.com/releases/august-2021-release ) to be removed from the navbar and included in the About dropdown, right?

More globally, I think it won't fit in the About dropdown but it would be cool to put links to Jagr and/or Adonis Mastery, as well as the two demo apps Jokes and Polls?

**Comment by thetutlage** [comment]
How about restructuring the entire nav as follows.

```
Learn
	Guides
	
	Reference
           Database
           Validator
           ... others
	
	Cookbooks

About
	Roadmap

	News

	Github

	Discord

	Twitter

	Branding guidelines

	Donate on Patreon


Resources
	Jokes app

	Polls app

	Jagr

	Adonis Mastery

	Packages
```

**Comment by Julien-R44** [comment]
Yes, that sounds great for me. I'm making the changes asap so this weekend I think, so don't hesitate if you have other suggestions before

**Comment by RomainLanz** [comment]
Hey @Julien-R44! 👋🏻 

Do you still plan to work on this?

**Comment by Julien-R44** [comment]
Hey ! 
I had totally forgot that PR 😀 ! However Virk took care of it so I'm closing this

**Pull request closed without merging**
