### PR TITLE
fix: minor typo in view truncate helper

### PR DESCRIPTION
**Pull request by KevinRouchut**

### CODE REVIEW

**Comment by RomainLanz** [comment]
Hey @KevinRouchut! 👋 

This is not a typo, we are truncating the string to 18 characters, so it ends like that.

**Comment by KevinRouchut** [comment]
I just checked again, with `completeWords: false`, the word `long` is truncated.

**Comment by KevinRouchut** [comment]
> I just checked again, with `completeWords: false`, the word `long` is truncated.

@RomainLanz

**Comment by RomainLanz** [comment]
Oooh, I read the diff the other way! 😅 
Thanks!

**Pull request merged**
