### PR TITLE
feat: added cookbook for custom type parsers with postgres

### PR DESCRIPTION
**Pull request by hlozancic**

### CODE REVIEW

**Comment by thetutlage** [comment]
Well written 👏. Can you please add YAML metadata similar to this file https://github.com/adonisjs/docs.adonisjs.com/blob/develop/content/cookbooks/socketio-with-adonisjs.md?plain=1#L1-L6

**Comment by hlozancic** [comment]
Added image from github. If you want I can upload to your cloudinary if needed.

**Comment by thetutlage** [comment]
Wonderful

**Comment by thetutlage** [comment]
Thanks for taking out time to write it :)

**Pull request merged**
