### PR TITLE
docs: use subpath exports to import core module

### PR DESCRIPTION
**Pull request by targos**
This can only land after a release with https://github.com/adonisjs/core/pull/2796 is published.

### CODE REVIEW

**Review by RomainLanz — APPROVED** [review]

**Comment by targos** [comment]
Actually, we should not only wait for a release of the subpath exports, but also for TypeScript to support this feature (otherwise it says that the module cannot be found).
I don't know why TS takes so much time to implement it...

**Comment by targos** [comment]
TS issue: https://github.com/microsoft/TypeScript/issues/33079

**Comment by thetutlage** [comment]
So, if I get it right. We should hold the releasing this https://github.com/adonisjs/core/pull/2796 until the TypeScript issue has been resolved?

**Comment by targos** [comment]
> So, if I get it right. We should hold the releasing this [adonisjs/core#2796](https://github.com/adonisjs/core/pull/2796) until the TypeScript issue has been resolved?

No, we should just hold telling people to use it.

**Comment by targos** [comment]
But we need https://github.com/adonisjs/core/pull/2813 to fix a bug I introduced in the other PR.

**Pull request closed without merging**
