### PR TITLE
feat: add dark mode

### PR DESCRIPTION
**Pull request by Julien-R44**
Hello ! 👋 
Last night I opened the documentation and my eyes almost burned! 😄 I thought It would be cool to add a dark mode, so I did it 

Some screenshots :
image

image

Let me know if anything is wrong or anything needs to be changed!

### CODE REVIEW

**Comment by Barbapapazes** [comment]
The left nav, gray color and active link aren't too dark (for contrast AA and AAA)?

But it's awesome!

**Comment by Julien-R44** [comment]
Here's another attempt with shades of gray/black and a darker purple based on Twitter suggestions :
image

With gray "brand color" : 
image

Let me know what you prefer and I will commit it !

**Comment by MaximeMRF** [comment]
I prefer the second one with gray "brand color"

**Comment by Barbapapazes** [comment]
> Here's another attempt with shades of gray/black and a darker purple based on Twitter suggestions :
> image
> 
> With gray "brand color" : 
> image
> 
> Let me know what you prefer and I will commit it !
> 

Prefer the second one but maybe with the brand colored header (not gray but violet)?

**Comment by Julien-R44** [comment]
I took the colors proposed by the other PR, so we should be good now ! 🙂

image

**Comment by thetutlage** [comment]
Thanks for the PR @Julien-R44. 

@babakfp Collaborating means listening to others and not simply proving you are right. I appreciate the efforts you have put into finalising colors. But there are many who wants to toggle regardless of the system color scheme. I myself do that all the time.

**Comment by babakfp** [comment]
@thetutlage

I was completely right.
I listened to people and that's why I created [this PR](https://github.com/adonisjs/docs.adonisjs.com/pull/130). People needed a dark mode and I provided it. As I said, this was for people not for the opinions of maintainers. The goal was to create a PR for the dark mode that was going to get merged as soon as possible (not like the current PR).

> I appreciate the efforts you have put into finalising colors.

You are welcome, but I didn't finish anything. It's just got copy-pasted here.

Current PR doesn't even include everything from my PR, it's missing some colors and fixes.

But thanks, It seems you are not like the other maintainers.

**Pull request merged**
